#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require __DIR__ . '/vendor/autoload.php';
} else {
    require __DIR__ . '/../../autoload.php';
}

$application = new \Ytake\Gardening\ConsoleApplication();
$application->registerCommand(
    new \Ytake\Gardening\SetUpCommand(new \Ytake\Gardening\Foundation\Filer)
);
$application->run();
